service: laravel

frameworkVersion: '2'

provider:
  name: aws
  region: ${env:MY_AWS_DEFAULT_REGION}
  stage: prod-mx
  runtime: provided.al2
  lambdaHashingVersion: 20201221
  environment:
    APP_NAME: ${env:APP_NAME}
    APP_ENV: ${env:APP_ENV}
    APP_KEY: ${env:APP_KEY}
    APP_DEBUG: ${env:APP_DEBUG}
    APP_URL: ${env:APP_URL}
    APP_LOCALE: ${env:APP_LOCALE}
    APP_FRONT_BASE_URL: ${env:APP_FRONT_BASE_URL}
    DEFAULT_COUNTRY: ${env:DEFAULT_COUNTRY}
    APP_SESSION_TTL: ${env:APP_SESSION_TTL}
    LOG_CHANNEL: ${env:LOG_CHANNEL}
    LOG_LEVEL: ${env:LOG_LEVEL}
    DB_CONNECTION: ${env:DB_CONNECTION}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_DATABASE: ${env:DB_DATABASE}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    BROADCAST_DRIVER: ${env:BROADCAST_DRIVER}
    CACHE_DRIVER: ${env:CACHE_DRIVER}
    FILESYSTEM_DRIVER: ${env:FILESYSTEM_DRIVER}
    QUEUE_CONNECTION: ${env:QUEUE_CONNECTION}
    SESSION_DRIVER: ${env:SESSION_DRIVER}
    SESSION_LIFETIME: ${env:SESSION_LIFETIME}
    MEMCACHED_HOST: ${env:MEMCACHED_HOST}
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
    REDIS_PORT: ${env:REDIS_PORT}
    MAIL_MAILER: ${env:MAIL_MAILER}
    MAIL_HOST: ${env:MAIL_HOST}
    MAIL_PORT: ${env:MAIL_PORT}
    MAIL_USERNAME: ${env:MAIL_USERNAME}
    MAIL_PASSWORD: ${env:MAIL_PASSWORD}
    MAIL_ENCRYPTION: ${env:MAIL_ENCRYPTION}
    MAIL_FROM_ADDRESS: ${env:MAIL_FROM_ADDRESS}
    MAIL_FROM_NAME: ${env:MAIL_FROM_NAME}
    MY_AWS_ACCESS_KEY_ID: ${env:MY_AWS_ACCESS_KEY_ID}
    MY_AWS_SECRET_ACCESS_KEY: ${env:MY_AWS_SECRET_ACCESS_KEY}
    MY_AWS_DEFAULT_REGION: ${env:MY_AWS_DEFAULT_REGION}
    MY_AWS_SES_ACCESS_KEY_ID: ${env:MY_AWS_SES_ACCESS_KEY_ID}
    MY_AWS_SES_SECRET_ACCESS_KEY: ${env:MY_AWS_SES_SECRET_ACCESS_KEY}
    MY_AWS_SES_DEFAULT_REGION: ${env:MY_AWS_SES_DEFAULT_REGION}
    MY_AWS_SES_CONFIG_SET: ${env:MY_AWS_SES_CONFIG_SET}
    MY_AWS_BUCKET: ${env:MY_AWS_BUCKET}
    MY_AWS_BUCKET_BASE_URL: ${env:MY_AWS_BUCKET_BASE_URL}
    MY_AWS_USE_PATH_STYLE_ENDPOINT: ${env:MY_AWS_USE_PATH_STYLE_ENDPOINT}
    MY_AWS_STORAGE_KEY: ${env:MY_AWS_STORAGE_KEY}
    MY_AWS_STORAGE_SECRET: ${env:MY_AWS_STORAGE_SECRET}
    MY_AWS_STORAGE_REGION: ${env:MY_AWS_STORAGE_REGION}
    MY_AWS_STORAGE_LINK_EMAIL: ${env:MY_AWS_STORAGE_LINK_EMAIL}
    PUSHER_APP_ID: ${env:PUSHER_APP_ID}
    PUSHER_APP_KEY: ${env:PUSHER_APP_KEY}
    PUSHER_APP_SECRET: ${env:PUSHER_APP_SECRET}
    PUSHER_APP_CLUSTER: ${env:PUSHER_APP_CLUSTER}
    MIX_PUSHER_APP_KEY: ${env:MIX_PUSHER_APP_KEY}
    MIX_PUSHER_APP_CLUSTER: ${env:MIX_PUSHER_APP_CLUSTER}
    PAY_API_KEY: ${env:PAY_API_KEY}
    PAY_DEFAULT_COUNTRY: ${env:PAY_DEFAULT_COUNTRY}
    PAY_PROVIDER: ${env:PAY_PROVIDER}
    SIMMA_VERSION_COUNTRY: ${env:SIMMA_VERSION_COUNTRY}
    SIMMA_API_HOST: ${env:SIMMA_API_HOST}
    SIMMA_ENCRYPT_KEY: ${env:SIMMA_ENCRYPT_KEY}
    PERSONAL_UNIQUE_DOCUMENT: ${env:PERSONAL_UNIQUE_DOCUMENT}
  iamRoleStatements:
    - Effect: Allow
      Action: s3:*
      Resource:
        - !Sub "${Storage.Arn}"
        - !Sub "${Storage.Arn}/*"

package:
  exclude:
    - node_modules/**
    - public/storage
    - resources/assets/**
    - storage/**
    - tests/**

plugins:
  - ./vendor/bref/bref

custom:
  myLambdaHandlerName: chosen-api-prod-mx

functions:
  web:
    handler: public/index.php
    name: ${self:custom.myLambdaHandlerName}-web
    timeout: 28
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - httpApi: "*"
  artisan:
    handler: artisan
    name: ${self:custom.myLambdaHandlerName}-artisan
    timeout: 120
    layers:
      - ${bref:layer.php-74}
      - ${bref:layer.console}
    events:
      - schedule:
          rate: rate(5 minutes)
          input: '"donor:add-into-package"'
      - schedule:
          rate: rate(10 minutes)
          input: '"simma:payment-donor"'
      - schedule:
          rate: rate(1 hour)
          input: '"hubspot:send-leads"'

resources:
  Resources:
    Storage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "chosen-api-prod-mx"
